function [outputArg1,outputArg2] = relSpkTms2NWB(relSpkTms, confStruct)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
outputArg1 = relSpkTms;
outputArg2 = confStruct;

nwb.units = types.core.Units('colnames',...
    {'spike_times', 'trials', 'waveforms'},...
    'description', 'Analysed Spike Events');

nwb.units.spike_times = types.hdmf_common.VectorData(...
    'description', 'timestamps of spikes');
% Line in a loop
nwb.units.addRow(...
        'id', ids(i), 'trials', eventTrials,'spike_times', eventTimes, 'waveforms', ses_ref,...
        'tablepath', '/units');

trials = types.core.TimeIntervals( ...
    'colnames', {'start_time', 'stop_time'}, ...
    'description', 'trial data and properties', ...
    'id', types.hdmf_common.ElementIdentifiers('data', 0:99), ...
    'start_time', types.hdmf_common.VectorData( ...
        'data', repmat(-0.3,1,100), ...
        'description','start time of trial in seconds' ...
    ), ...
    'stop_time', types.hdmf_common.VectorData( ...
        'data', repmat(0.4,1,100), ...
        'description','end of each trial in seconds' ...
    ));

for ct = 1:Nt

end
end