outDir = 'Z:\SC Anatomy paper data\Anaesthetised';
% Session path
sessionPath = fullfile("Z:\Emilio\SuperiorColliculusExperiments\Anaesthetised\M24_220224_SC-E1_IO&Freq");
% Coordinates from file name or labbook
%(+x = posterior AP, +y = inferior DV, +z = subject s right ML)
coords = [3600, 2000, 1500];
% Used probe
cmGeometry = 'E';
% Date (and time) of session start
sessionDate = datetime('220224','InputFormat','yyMMdd'); sessionDate.Format = 'yyMMdd';
% Identifier
identifier = ['Rbp4-24_' char(sessionDate)];
genotype = 'Rbp4cre-ChR2';

birthdate = datetime(sessionDate,'InputFormat','dd.MM.yy');

mouseSource = 'IBF';
mouseSex = 'unknown';

selected_condition = '32 mW';
experimentDescription = 'MC- and BC-L5 optogenetic stimulation in an Rbp4cre ChR2 mouse';

nwbObj = convertSession2NWB(sessionPath, ...
    "SessionDate", sessionDate, ...
    "Coordinates", coords, ...
    "ConditionSelection", selected_condition,...
    "OutDir", outDir, ...
    "Birthdate", birthdate, ...
    "Identifier", identifier, ...
    "ExperimentDescription", experimentDescription, ...
    "MouseSex", mouseSex, ...
    "MouseSource", mouseSource, ...
    "Genotype", genotype, ...
    "chanMapGeometry", cmGeometry);