outDir = 'Z:\SC Anatomy paper data\Roller';
sessionPath = fullfile('Z:\Emilio\SuperiorColliculusExperiments\Roller\Batch7_ephys\MC\GADe48\220713_C_DVnone\ephys_E');
coords = [3600, 2100, 1500];
birthdate = datetime(2022, 1, 14);
nwbObj = convertSession2NWB(sessionPath, ...
    "Coordinates", coords, ...
    "ConditionSelection", 'Control Puff',...
    "OutDir", outDir, ...
    "Birthdate", birthdate);