outDir = 'Z:\SC Anatomy paper data\Anaesthetised';
sessionPath = "Z:\Emilio\SuperiorColliculusExperiments\Anaesthetised\M12_190414_SC_E1\M12.1_DV1600_ML1000_AP3800";
%(+x = posterior AP, +y = inferior DV, +z = subject s right ML)
coords = [3800, 1600, 1000];
cmGeometry = 'E';
sessionDate = datetime('190414','InputFormat','yyMMdd'); sessionDate.Format = 'yyMMdd';
birthdate = datetime('06.11.19','InputFormat','dd.MM.yy');
mouseSource = 'IBF';
mouseSex = 'female';
selected_condition = 'Control Laser';
experimentDescription = 'MC- and BC-L5 optogenetic stimulation in an Rbp4cre ChR2 mouse';
identifier = ['Rbp4-12.1_' char(sessionDate)];
nwbObj = convertSession2NWB(sessionPath, ...
    "SessionDate", sessionDate, ...
    "Coordinates", coords, ...
    "ConditionSelection", selected_condition,...
    "OutDir", outDir, ...
    "Birthdate", birthdate, ...
    "Identifier", identifier, ...
    "ExperimentDescription", experimentDescription, ...
    "MouseSex", mouseSex, ...
    "MouseSource", mouseSource, ...
    "chanMapGeometry", cmGeometry);