function plotLogPSTH(PSTHstruct, varargin)
%PLOTLOGPSTH takes the logPSTH structure generated by getLogTimePSTH and
%plots the PSTH per condition, and their mean.
%   Detailed explanation goes here
%Emilio Isaias-Camacho @ GrohLab 2021

%% Parse inputs
p = inputParser;

% Required arguments auxiliary function and variables
pfn = ["LogPSTH", "Log10TimeAxis", "TimeAxis", "ConditionNames",...
    "DeltaLogStep"];
checkStruct = @(x) any([isstruct(x), isfield(x, pfn)]);

% Required parameters
% none so far

% Optional parameters
% none so far, maybe ordering?

p.addRequired('PSTHstruct', checkStruct);

p.KeepUnmatched = true;

p.parse(PSTHstruct, varargin{:});

PSTHstruct = p.Results.PSTHstruct;

%% Auxiliary variables
expSubs = @(x) x(1):x(2);
% PSTH per condition
[Ncl, Nbin, Ncond] = size(PSTHstruct.LogPSTH);
condPsth = squeeze(mean(PSTHstruct.LogPSTH,1)); 
condPsth = condPsth./sum(condPsth);

% Comparison between conditions
permCond = nchoosek(1:Ncond,2); Nperm = size(permCond,1);
% Figure for displaying PSTHs per condition
natFig = figure('Visible','off'); natAx = gobjects(Ncond+1,1);

logMeanEdges = [2,1; 3,0]*[Ncond;1];
natAx(Ncond + 1) = subplot(3, Ncond, expSubs(logMeanEdges));
semilogx(natAx(Ncond + 1), PSTHstruct.TimeAxis, condPsth); 
legend(natAx(Ncond + 1), PSTHstruct.ConditionNames.cellstr);
xticklabels(natAx(Ncond + 1), xticks(natAx(Ncond + 1))*1e3);
xlim(natAx(Ncond + 1), PSTHstruct.TimeAxis([1,Nbin]));
for ccond = 1:Ncond
    imgMat = [ccond, 0; ccond, Ncond];
    natAx(ccond) = subplot(3, Ncond, imgMat * [1;1]); 
    imagesc(natAx(ccond), 'XData', PSTHstruct.Log10TimeAxis, 'YData', 1:Ncl,...
        'CData', PSTHstruct.LogPSTH(:,:,ccond));
    xticklabels(natAx(ccond), 10.^(xticks(natAx(ccond))+3));
    title(natAx(ccond), PSTHstruct.ConditionNames(ccond));
    ylim(natAx(ccond), [1, Ncl])
end
arrayfun(@(x) xlim(x, PSTHstruct.Log10TimeAxis([1,Nbin])), natAx(1:Ncond));
natFig.Visible = 'on';
% Figure for displaying a comparison between condition permutations
permFig = figure('Visible','off');


end

